/**
 * Server-only settings read from the environment at request time.
 * Never import this module from a client component.
 */

/** Base URL of the FastAPI backend (reachable from this server only). */
export function backendUrl(): string {
  return (process.env.BACKEND_URL ?? "http://127.0.0.1:8500").replace(/\/$/, "");
}

/** Token this server presents to the backend (`X-Service-Token`); generated by the installer. */
export function bffServiceToken(): string {
  const token = process.env.BFF_SERVICE_TOKEN;
  if (!token || token.length < 32) throw new Error("BFF_SERVICE_TOKEN must be set to at least 32 characters");
  return token;
}

/** HMAC secret signing the anonymous visitor cookie. */
export function visitorCookieSecret(): string {
  const secret = process.env.VISITOR_COOKIE_SECRET;
  if (!secret || secret.length < 32) {
    throw new Error("VISITOR_COOKIE_SECRET must be set to at least 32 characters");
  }
  return secret;
}

/** Origins allowed to embed the widget (WIDGET_ALLOWED_PARENTS; the installer sets it to HOST_ORIGIN). */
export function widgetAllowedParents(): string[] {
  return (process.env.WIDGET_ALLOWED_PARENTS ?? "")
    .split(/[\s,]+/)
    .map((origin) => origin.replace(/\/$/, ""))
    .filter(Boolean);
}

/** Whether cookies must be marked Secure (always true outside local development). */
export function secureCookies(): boolean {
  return process.env.NODE_ENV === "production";
}
