"""
Deploy and roll back tagged releases on one box.

``deploy <tag>``: pull the tag's images, back up the database, make sure the
application's database role exists (with its current password), start the
stack (the ``migrate`` service applies Alembic migrations before the API
starts) and wait until it is healthy. Every successful deploy is appended to
``.deploy_history``; ``rollback`` redeploys the previous entry.
"""

# Standard library imports
import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, List, Optional

# Local imports
from .backup import BackupManager
from .compose import Compose
from .env_file import EnvFile
from .layout import InstallLayout, copy_templates
from .runner import CommandError

logger = logging.getLogger(__name__)

#: Docker image tag syntax.
TAG_PATTERN = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$")
ENV_HEADER = (
    "Generated by the chatbot installer (`chatbot install`).\n"
    "Secrets are generated per box; never copy this file between deployments."
)
APP_ROLE_SCRIPT = "/docker-entrypoint-initdb.d/10-app-role.sh"
#: Services that must be healthy for a deploy to count as done.
HEALTH_GATE_SERVICES = ("postgres", "model-server", "api", "web", "admin", "caddy")
HEALTH_TIMEOUT_SECONDS = 900


class DeployError(RuntimeError):
    """A deploy failed; the message says how to recover."""


@dataclass(frozen=True)
class DeployResult:
    """What a successful deploy changed."""

    tag: str
    previous_tag: Optional[str]
    backup_name: Optional[str]


class Deployer:
    """Moves one box between tagged releases."""

    def __init__(
        self,
        layout: InstallLayout,
        compose: Compose,
        backups: Callable[[], Optional[BackupManager]],
        out: Callable[[str], None] = print,
        templates_dir: Optional[Path] = None,
    ):
        """
        Args:
            layout: The install directory.
            compose: Compose for the stack.
            backups: Builds the backup manager (``None`` when no target is configured yet).
            out: Progress output for the operator.
            templates_dir: This release's compose file and deploy assets, copied
                in before pulling (``None`` keeps the files already installed).
        """
        self._templates_dir = templates_dir
        self._layout = layout
        self._compose = compose
        self._backups = backups
        self._out = out

    def history(self) -> List[str]:
        """Successfully deployed tags, oldest first."""
        if not self._layout.history_file.exists():
            return []
        return [line.strip() for line in self._layout.history_file.read_text(encoding="utf-8").splitlines() if line.strip()]

    def _record(self, tag: str) -> None:
        """Append ``tag`` to the history (collapsing an immediate repeat)."""
        history = self.history()
        if not history or history[-1] != tag:
            history.append(tag)
        self._layout.history_file.write_text("\n".join(history) + "\n", encoding="utf-8")

    def previous_tag(self) -> Optional[str]:
        """The last deployed tag before the current one, if any."""
        history = self.history()
        current = history[-1] if history else None
        for tag in reversed(history):
            if tag != current:
                return tag
        return None

    def deploy(self, tag: str, backup: bool = True) -> DeployResult:
        """
        Deploy ``tag``.

        Raises:
            DeployError: Invalid tag or a failed step (with recovery instructions).
        """
        if not TAG_PATTERN.match(tag):
            raise DeployError(f"Invalid image tag {tag!r}")
        env = EnvFile(self._layout.env_file).load()
        previous = self.history()[-1] if self.history() else None
        env.set("IMAGE_TAG", tag)
        env.save(ENV_HEADER)
        if self._templates_dir is not None:
            copy_templates(self._templates_dir, self._layout.root)
        backup_name = None
        try:
            self._out(f"Pulling images for {tag}…")
            self._compose.pull()
            if backup and self._compose.is_running("postgres"):
                manager = self._backups()
                if manager is not None:
                    self._out("Backing up the database before migrating…")
                    backup_name = manager.create(f"pre-{tag.lower().replace('_', '-')}"[:40]).name
            self._out("Starting the database…")
            self._compose.up(["postgres"])
            self._compose.wait_healthy(["postgres"], HEALTH_TIMEOUT_SECONDS)
            self._compose.exec(
                "postgres", ["sh", APP_ROLE_SCRIPT],
                env={"POSTGRES_APP_PASSWORD": env.get("POSTGRES_APP_PASSWORD", "")},
            )
            self._out("Migrating and starting every service…")
            self._compose.up()
            self._compose.wait_healthy(HEALTH_GATE_SERVICES, HEALTH_TIMEOUT_SECONDS)
        except (CommandError, OSError) as exc:
            logger.exception("Deploy of %s failed", tag)
            raise DeployError(self._recovery_hint(tag, previous, backup_name, exc)) from exc
        self._record(tag)
        self._out(f"Deployed {tag}.")
        return DeployResult(tag, previous, backup_name)

    @staticmethod
    def _recovery_hint(tag: str, previous: Optional[str], backup_name: Optional[str], exc: Exception) -> str:
        """Operator instructions after a failed deploy."""
        lines = [f"Deploy of {tag} failed: {exc}"]
        if previous:
            lines.append(f"Roll back with:   chatbot rollback {previous}")
        if backup_name:
            lines.append(f"If the database was migrated, restore it with:   chatbot restore {backup_name}")
        return "\n".join(lines)

    def rollback(self, tag: Optional[str] = None) -> DeployResult:
        """
        Redeploy ``tag`` (default: the previous tag in the history).

        Migrations are not reverted automatically: the pre-deploy backup of
        the failed release restores the matching schema if one is needed.

        Raises:
            DeployError: No previous release, or the redeploy failed.
        """
        target = tag or self.previous_tag()
        if target is None:
            raise DeployError("Nothing to roll back to: only one release was ever deployed here")
        self._out(f"Rolling back to {target}…")
        return self.deploy(target)
