"""
Settings of the model-server (the one process holding the GPU models) and of its clients.

With ``MODEL_SERVER_URL`` unset every process loads its own models, as in a
native development run; under docker compose api and ingestion-worker call
the model-server over the internal network.
"""

# Local imports
from .env import env_int, env_str


class ModelServerConfig:
    """Where the model-server is and how it schedules work."""

    @staticmethod
    def MODEL_SERVER_URL() -> str:
        """Base URL of the model-server; empty = load models in this process."""
        return env_str("MODEL_SERVER_URL", "").rstrip("/")

    @staticmethod
    def MODEL_SERVER_TOKEN() -> str:
        """Shared secret between the model-server and its clients (generated by the installer)."""
        return env_str("MODEL_SERVER_TOKEN", "")

    @staticmethod
    def MODEL_SERVER_PORT() -> int:
        """Port the model-server listens on (internal network only)."""
        return env_int("MODEL_SERVER_PORT", 8600)

    @staticmethod
    def MODEL_SERVER_SLOTS() -> int:
        """Model calls running at once on the GPU."""
        return max(2, env_int("MODEL_SERVER_SLOTS", 3))

    @staticmethod
    def MODEL_SERVER_INGESTION_SLOTS() -> int:
        """Of those, how many may be ingestion work (OCR, bulk embedding); 1 = one OCR page at a time."""
        return max(1, env_int("MODEL_SERVER_INGESTION_SLOTS", 1))

    @staticmethod
    def MODEL_SERVER_TIMEOUT_SECONDS() -> int:
        """Client timeout for chat-path calls (query embedding, reranking)."""
        return env_int("MODEL_SERVER_TIMEOUT_SECONDS", 30)

    @staticmethod
    def MODEL_SERVER_INGESTION_TIMEOUT_SECONDS() -> int:
        """Client timeout for ingestion calls (a page of OCR, a batch of passages)."""
        return env_int("MODEL_SERVER_INGESTION_TIMEOUT_SECONDS", 600)
